/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eve_rem;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vaibhav
 */
public class SMS_API extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;
    
    /**
     * Creates new form SMS_API
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public SMS_API() throws SQLException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtDesc.setEditable(false);
        txtDesc.setBorder(null);
        txtDesc.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        
        jLabel3.setForeground(new Color(195,128,255));
        Font ft = jLabel3.getFont();
        Map attributes = ft.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,TextAttribute.UNDERLINE_ON);
        jLabel3.setFont(ft.deriveFont(attributes));
        int count = row_count();
        if (count == 0)
            btnSet.setText("Submit");
        else
        {
            btnSet.setText("Update");
            txtLink.setText(Eve_Rem.pubSMSAPI);
        }
    }

    public int row_count() throws SQLException, ClassNotFoundException
    {
        int count = 0;
        Connection conn1 = null;
        PreparedStatement pstmt = null;
        ResultSet rs1 = null;
        
        Class.forName("com.mysql.jdbc.Driver");
        conn1 = DriverManager.getConnection("jdbc:mysql:///eve_remi", "root", "Vaibhav159"); 
        pstmt = conn1.prepareStatement("Select count(*) from eve_remi.smsapi");
        rs1 = pstmt.executeQuery();
        if(rs1.next())
        {
            count = rs1.getInt("count(*)");
        }
        return count;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSet = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lblDelete2 = new javax.swing.JLabel();
        lblDelete3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("API Token");

        txtLink.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLink.setToolTipText("API Token");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Set SMS API");

        btnSet.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSet.setText("Submit");
        btnSet.setToolTipText("Submit");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtDesc.setBackground(new java.awt.Color(234, 234, 234));
        txtDesc.setColumns(1);
        txtDesc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDesc.setLineWrap(true);
        txtDesc.setRows(1);
        txtDesc.setTabSize(0);
        txtDesc.setText("Note :- You can get API Token from www.pay2all.in by making a simple account and click \t               on SMS API, but before purchase the SMS bundle. For more details refer the link at              given below.\n\nDisclaimer :- Check API Token before submit, wrong API Token cannot work.");
        txtDesc.setToolTipText("");
        txtDesc.setMinimumSize(new java.awt.Dimension(1, 1));
        txtDesc.setName(""); // NOI18N
        txtDesc.setPreferredSize(new java.awt.Dimension(108, 20));
        jScrollPane1.setViewportView(txtDesc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("https://youtu.be/2Tlp1aya4cc");
        jLabel3.setToolTipText(jLabel3.getText());
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        lblDelete2.setIcon(new javax.swing.ImageIcon("D:\\Photos\\Use GIF Image\\hand_right.gif")); // NOI18N
        lblDelete2.setToolTipText("");
        lblDelete2.setAlignmentX(20);
        lblDelete2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDelete2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDelete2MouseClicked(evt);
            }
        });

        lblDelete3.setIcon(new javax.swing.ImageIcon("D:\\Photos\\Use GIF Image\\hand_left.gif")); // NOI18N
        lblDelete3.setToolTipText("");
        lblDelete3.setAlignmentX(20);
        lblDelete3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDelete3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDelete3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(lblDelete2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(lblDelete3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btnSet, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel5)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnSet, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDelete3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql:///eve_remi", "root", "Vaibhav159");
            if ("Submit".equals(btnSet.getText()))
            {
                int res = JOptionPane.showConfirmDialog(this, "Are you sure to Submit SMS API?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(res == JOptionPane.YES_OPTION)
                {
                    stmt = conn.prepareStatement("insert into eve_remi.smsapi values(?,?)");
                    stmt.setString(1, txtLink.getText());
                    stmt.setInt(2, 1);
                    stmt.executeUpdate();
                    dispose();
                }
                else
                {
                    txtLink.setText("");
                    txtLink.requestFocus();
                }
            }
            else
            {
                int res = JOptionPane.showConfirmDialog(this, "Are you sure to Submit SMS API?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(res == JOptionPane.YES_OPTION)
                {
                    stmt = conn.prepareStatement("update eve_remi.smsapi set APIToken=?,onoff=?");
                    stmt.setString(1, txtLink.getText());
                    stmt.setInt(2, 1);
                    stmt.executeUpdate();
                    dispose();
                }
                else
                {
                    txtLink.setText("");
                    txtLink.requestFocus();
                }
            }
        }
        catch(SQLException e)
        {
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SMS_API.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            Desktop.getDesktop().browse(new URL("https://youtu.be/2Tlp1aya4cc").toURI());
        } catch (MalformedURLException ex) {
            Logger.getLogger(SMS_API.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(SMS_API.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lblDelete2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete2MouseClicked
    
    }//GEN-LAST:event_lblDelete2MouseClicked

    private void lblDelete3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelete3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDelete3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMS_API.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new SMS_API().setVisible(true);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(SMS_API.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDelete2;
    private javax.swing.JLabel lblDelete3;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtLink;
    // End of variables declaration//GEN-END:variables
}
